<?php
/**
 * Posts page and site home.
 *
 * @package Pergrazia
 */

get_header();
$pergrazia_header_image = get_header_image();
$pergrazia_is_first_page = ! is_paged();
$pergrazia_hero_classes  = 'site-hero__image';
$pergrazia_hero_src      = $pergrazia_header_image;

if ( $pergrazia_header_image && str_contains( $pergrazia_header_image, '/pergrazia-hero.' ) ) {
	$pergrazia_hero_classes .= ' is-pergrazia-artwork is-pergrazia-new-artwork';
} elseif ( $pergrazia_header_image && str_contains( $pergrazia_header_image, '/pergrazia-hero-original.' ) ) {
	$pergrazia_hero_classes .= ' is-pergrazia-artwork is-pergrazia-original-artwork';
}

if ( $pergrazia_hero_src && str_contains( $pergrazia_hero_src, '/themes/pergrazia/assets/images/' ) ) {
	$pergrazia_hero_src = add_query_arg( 'ver', PERGRAZIA_VERSION, $pergrazia_hero_src );
}

$pergrazia_newsletter_form = '';

if ( $pergrazia_is_first_page && shortcode_exists( 'mc4wp_form' ) ) {
	$pergrazia_newsletter_form = do_shortcode( '[mc4wp_form element_class="home-newsletter__form"]' );
}

$pergrazia_donate_url = (string) get_theme_mod( 'pergrazia_donate_url', '' );
?>
<main id="main-content">
	<?php if ( $pergrazia_is_first_page ) : ?>
		<?php if ( $pergrazia_header_image ) : ?>
			<section class="site-hero" aria-label="<?php esc_attr_e( 'Per Grazia artwork', 'pergrazia' ); ?>">
				<figure class="<?php echo esc_attr( $pergrazia_hero_classes ); ?>">
					<img src="<?php echo esc_url( $pergrazia_hero_src ); ?>" width="<?php echo esc_attr( (string) get_custom_header()->width ); ?>" height="<?php echo esc_attr( (string) get_custom_header()->height ); ?>" alt="">
				</figure>
			</section>
		<?php endif; ?>
		<section class="home-journal" aria-labelledby="home-journal-title">
			<header class="home-intro reading-width">
				<p class="eyebrow"><?php esc_html_e( 'Faith, grace and life', 'pergrazia' ); ?></p>
				<h1 id="home-journal-title"><?php esc_html_e( 'Thoughts for a lived faith.', 'pergrazia' ); ?></h1>
			</header>
	<?php else : ?>
		<header class="archive-header">
			<div class="shell">
				<p class="archive-kicker"><?php esc_html_e( 'Journal', 'pergrazia' ); ?></p>
				<h1><?php esc_html_e( 'Latest articles', 'pergrazia' ); ?></h1>
			</div>
		</header>
	<?php endif; ?>

	<section class="post-list shell" aria-label="<?php esc_attr_e( 'Latest articles', 'pergrazia' ); ?>">
		<?php if ( have_posts() ) : ?>
			<?php $pergrazia_position = 0; ?>
			<?php while ( have_posts() ) : ?>
				<?php the_post(); ?>
				<?php if ( 0 === $pergrazia_position && ! is_paged() ) : ?>
					<?php get_template_part( 'template-parts/content', 'featured' ); ?>
					<div class="post-grid">
				<?php else : ?>
					<?php if ( 0 === $pergrazia_position ) : ?><div class="post-grid"><?php endif; ?>
					<?php get_template_part( 'template-parts/content', 'card' ); ?>
				<?php endif; ?>
				<?php ++$pergrazia_position; ?>
			<?php endwhile; ?>
			</div>

			<?php
			the_posts_pagination(
				array(
					'mid_size'  => 1,
					'prev_text' => __( 'Previous', 'pergrazia' ),
					'next_text' => __( 'Next', 'pergrazia' ),
				)
			);
			?>
		<?php else : ?>
			<?php get_template_part( 'template-parts/content', 'none' ); ?>
		<?php endif; ?>
	</section>

	<?php if ( $pergrazia_is_first_page ) : ?>
		</section>

		<section class="home-newsletter" aria-labelledby="home-newsletter-title">
			<div class="home-newsletter__inner shell">
				<div class="home-newsletter__copy">
					<p class="eyebrow"><?php esc_html_e( 'Stay in touch', 'pergrazia' ); ?></p>
					<h2 id="home-newsletter-title"><?php esc_html_e( 'A quiet note in your inbox.', 'pergrazia' ); ?></h2>
					<p><?php esc_html_e( 'Receive new reflections and updates from Per Grazia. No noise, only what matters.', 'pergrazia' ); ?></p>
				</div>
				<div class="home-newsletter__form-wrap">
					<?php if ( $pergrazia_newsletter_form ) : ?>
						<?php
						// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Trusted form markup generated by Mailchimp for WordPress.
						echo $pergrazia_newsletter_form;
						?>
					<?php else : ?>
						<p class="home-newsletter__pending"><?php esc_html_e( 'The newsletter sign-up form will be available soon.', 'pergrazia' ); ?></p>
					<?php endif; ?>
				</div>
			</div>
		</section>

		<section class="home-donate" aria-labelledby="home-donate-title">
			<div class="home-donate__inner shell">
				<div class="home-donate__copy">
					<p class="eyebrow"><?php esc_html_e( 'Support Per Grazia', 'pergrazia' ); ?></p>
					<h2 id="home-donate-title"><?php esc_html_e( 'Help this space keep growing.', 'pergrazia' ); ?></h2>
					<p><?php esc_html_e( 'Your contribution helps Per Grazia continue publishing thoughtful, independent reflections and reaching new readers.', 'pergrazia' ); ?></p>
				</div>
				<div class="home-donate__action">
					<?php if ( $pergrazia_donate_url ) : ?>
						<a class="button" href="<?php echo esc_url( $pergrazia_donate_url ); ?>"><?php esc_html_e( 'Donate', 'pergrazia' ); ?></a>
					<?php else : ?>
						<span class="button button--pending" aria-disabled="true"><?php esc_html_e( 'Donation link coming soon', 'pergrazia' ); ?></span>
					<?php endif; ?>
				</div>
			</div>
		</section>
	<?php endif; ?>
</main>
<?php
get_footer();
