<?php
/**
 * Remove database state left by Really Simple Security and Super Page Cache.
 */

return static function () {
	global $wpdb;

	$plugin_files = array(
		'really-simple-ssl/rlrsssl-really-simple-ssl.php',
		'wp-cloudflare-page-cache/wp-cloudflare-super-page-cache.php',
	);

	$delete_prefixed_rows = static function ( string $table, string $column, array $prefixes ) use ( $wpdb ): void {
		foreach ( $prefixes as $prefix ) {
			$result = $wpdb->query(
				$wpdb->prepare(
					"DELETE FROM {$table} WHERE {$column} LIKE %s",
					$wpdb->esc_like( $prefix ) . '%'
				)
			);

			if ( false === $result ) {
				throw new RuntimeException( "Failed to delete {$prefix} records from {$table}: {$wpdb->last_error}" );
			}
		}
	};

	$drop_table = static function ( string $table ) use ( $wpdb ): void {
		if ( ! preg_match( '/^[A-Za-z0-9_]+$/', $table ) ) {
			throw new RuntimeException( "Refusing to drop an invalid table name: {$table}" );
		}

		if ( false === $wpdb->query( "DROP TABLE IF EXISTS `{$table}`" ) ) {
			throw new RuntimeException( "Failed to drop {$table}: {$wpdb->last_error}" );
		}
	};

	$cleanup_action_scheduler = static function () use ( $wpdb ): void {
		$actions_table = $wpdb->prefix . 'actionscheduler_actions';
		$groups_table  = $wpdb->prefix . 'actionscheduler_groups';
		$logs_table    = $wpdb->prefix . 'actionscheduler_logs';

		foreach ( array( $actions_table, $groups_table, $logs_table ) as $table ) {
			$found = $wpdb->get_var(
				$wpdb->prepare( 'SHOW TABLES LIKE %s', $wpdb->esc_like( $table ) )
			);

			if ( $found !== $table ) {
				return;
			}
		}

		$queries = array(
			"DELETE logs FROM `{$logs_table}` logs INNER JOIN `{$actions_table}` actions ON actions.action_id = logs.action_id INNER JOIN `{$groups_table}` action_groups ON action_groups.group_id = actions.group_id WHERE action_groups.slug = 'spc'",
			"DELETE actions FROM `{$actions_table}` actions INNER JOIN `{$groups_table}` action_groups ON action_groups.group_id = actions.group_id WHERE action_groups.slug = 'spc'",
			"DELETE FROM `{$groups_table}` WHERE slug = 'spc'",
		);

		foreach ( $queries as $query ) {
			if ( false === $wpdb->query( $query ) ) {
				throw new RuntimeException( "Failed to remove Super Page Cache scheduled actions: {$wpdb->last_error}" );
			}
		}
	};

	$cleanup_blog = static function () use (
		$wpdb,
		$plugin_files,
		$delete_prefixed_rows,
		$drop_table,
		$cleanup_action_scheduler
	): void {
		$active_plugins = get_option( 'active_plugins', array() );
		if ( is_array( $active_plugins ) ) {
			$filtered_plugins = array_values( array_diff( $active_plugins, $plugin_files ) );
			if ( $filtered_plugins !== $active_plugins ) {
				update_option( 'active_plugins', $filtered_plugins );
			}
		}

		$delete_prefixed_rows(
			$wpdb->options,
			'option_name',
			array(
				'rsssl_',
				'rlrsssl_',
				'_transient_rsssl_',
				'_transient_timeout_rsssl_',
				'_transient_rlrsssl_',
				'_transient_timeout_rlrsssl_',
				'_site_transient_rsssl_',
				'_site_transient_timeout_rsssl_',
				'_site_transient_rlrsssl_',
				'_site_transient_timeout_rlrsssl_',
				'swcfpc_',
				'spc_',
				'_transient_spc_',
				'_transient_timeout_spc_',
				'_site_transient_spc_',
				'_site_transient_timeout_spc_',
				'wp_cloudflare_page_cache_',
			)
		);

		foreach ( array( 'cf_rule_update_failed', 'cf_will_run_free_to_pro_migrations' ) as $option ) {
			delete_option( $option );
		}

		$result = $wpdb->delete( $wpdb->postmeta, array( 'meta_key' => 'swcfpc_bypass_cache' ), array( '%s' ) );
		if ( false === $result ) {
			throw new RuntimeException( "Failed to delete Super Page Cache post metadata: {$wpdb->last_error}" );
		}

		$cron = _get_cron_array();
		if ( is_array( $cron ) ) {
			$hooks = array();
			foreach ( $cron as $events ) {
				foreach ( array_keys( $events ) as $hook ) {
					if ( str_starts_with( $hook, 'rsssl_' ) || str_starts_with( $hook, 'swcfpc_' ) ) {
						$hooks[ $hook ] = true;
					}
				}
			}

			foreach ( array_keys( $hooks ) as $hook ) {
				$result = wp_clear_scheduled_hook( $hook );
				if ( false === $result || is_wp_error( $result ) ) {
					throw new RuntimeException( "Failed to clear the {$hook} cron hook." );
				}
			}
		}

		$administrator = get_role( 'administrator' );
		if ( $administrator && $administrator->has_cap( 'manage_security' ) ) {
			$administrator->remove_cap( 'manage_security' );
		}

		$cleanup_action_scheduler();
		$drop_table( $wpdb->prefix . 'spc_assets_rules' );

		// Remove any custom-login rewrite rule that was generated by RSSSL.
		flush_rewrite_rules( false );
	};

	$original_blog_id = get_current_blog_id();
	$site_ids         = is_multisite()
		? get_sites( array( 'fields' => 'ids', 'number' => 0 ) )
		: array( $original_blog_id );

	foreach ( $site_ids as $site_id ) {
		$switched = is_multisite() && (int) $site_id !== get_current_blog_id();
		if ( $switched ) {
			switch_to_blog( (int) $site_id );
		}

		try {
			$cleanup_blog();
		} finally {
			if ( $switched ) {
				restore_current_blog();
			}
		}
	}

	foreach ( array( 'rsssl_', 'rlrsssl_' ) as $fragment ) {
		$result = $wpdb->query(
			$wpdb->prepare(
				"DELETE FROM {$wpdb->usermeta} WHERE meta_key LIKE %s",
				'%' . $wpdb->esc_like( $fragment ) . '%'
			)
		);

		if ( false === $result ) {
			throw new RuntimeException( "Failed to delete {$fragment} user metadata: {$wpdb->last_error}" );
		}
	}

	if ( is_multisite() ) {
		$delete_prefixed_rows(
			$wpdb->sitemeta,
			'meta_key',
			array(
				'rsssl_',
				'rlrsssl_',
				'_site_transient_rsssl_',
				'_site_transient_timeout_rsssl_',
				'_site_transient_rlrsssl_',
				'_site_transient_timeout_rlrsssl_',
				'swcfpc_',
				'spc_',
				'_site_transient_spc_',
				'_site_transient_timeout_spc_',
				'wp_cloudflare_page_cache_',
			)
		);

		foreach ( array( 'cf_rule_update_failed', 'cf_will_run_free_to_pro_migrations' ) as $option ) {
			delete_site_option( $option );
		}

		$network_plugins = get_site_option( 'active_sitewide_plugins', array() );
		if ( is_array( $network_plugins ) ) {
			$changed = false;
			foreach ( $plugin_files as $plugin_file ) {
				if ( isset( $network_plugins[ $plugin_file ] ) ) {
					unset( $network_plugins[ $plugin_file ] );
					$changed = true;
				}
			}

			if ( $changed ) {
				update_site_option( 'active_sitewide_plugins', $network_plugins );
			}
		}
	}

	foreach (
		array(
			'rsssl_csp_log',
			'rsssl_xmlrpc',
			'rsssl_country',
			'rsssl_login_attempts',
			'rsssl_geo_block',
			'rsssl_event_logs',
		) as $table_suffix
	) {
		$drop_table( $wpdb->base_prefix . $table_suffix );
	}

	// Bulk SQL bypasses WordPress's object-cache invalidation.
	wp_cache_flush();
};
